/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: platform.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as platform_pb from './platform_pb';


export class PlatformServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateNewPlatform = new grpcWeb.MethodDescriptor(
    '/proto.PlatformService/CreateNewPlatform',
    grpcWeb.MethodType.UNARY,
    platform_pb.NewPlatform,
    platform_pb.Platform,
    (request: platform_pb.NewPlatform) => {
      return request.serializeBinary();
    },
    platform_pb.Platform.deserializeBinary
  );

  createNewPlatform(
    request: platform_pb.NewPlatform,
    metadata: grpcWeb.Metadata | null): Promise<platform_pb.Platform>;

  createNewPlatform(
    request: platform_pb.NewPlatform,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: platform_pb.Platform) => void): grpcWeb.ClientReadableStream<platform_pb.Platform>;

  createNewPlatform(
    request: platform_pb.NewPlatform,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: platform_pb.Platform) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.PlatformService/CreateNewPlatform',
        request,
        metadata || {},
        this.methodDescriptorCreateNewPlatform,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.PlatformService/CreateNewPlatform',
    request,
    metadata || {},
    this.methodDescriptorCreateNewPlatform);
  }

  methodDescriptorGetPlatformList = new grpcWeb.MethodDescriptor(
    '/proto.PlatformService/GetPlatformList',
    grpcWeb.MethodType.UNARY,
    platform_pb.PlatformListRequest,
    platform_pb.PlatformListResponse,
    (request: platform_pb.PlatformListRequest) => {
      return request.serializeBinary();
    },
    platform_pb.PlatformListResponse.deserializeBinary
  );

  getPlatformList(
    request: platform_pb.PlatformListRequest,
    metadata: grpcWeb.Metadata | null): Promise<platform_pb.PlatformListResponse>;

  getPlatformList(
    request: platform_pb.PlatformListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: platform_pb.PlatformListResponse) => void): grpcWeb.ClientReadableStream<platform_pb.PlatformListResponse>;

  getPlatformList(
    request: platform_pb.PlatformListRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: platform_pb.PlatformListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.PlatformService/GetPlatformList',
        request,
        metadata || {},
        this.methodDescriptorGetPlatformList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.PlatformService/GetPlatformList',
    request,
    metadata || {},
    this.methodDescriptorGetPlatformList);
  }

}

